/** Schema.org entity fragments. Imported by pages via `slot="head"`. */

export const serviceSchemas = [
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-learningmate',
    name: 'LearningMate',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: '教育コンテンツ',
    description: 'LLM活用の教育コンテンツ企画・制作・販売',
    inLanguage: 'ja',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-ai-loop',
    name: 'AI-Loop',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'マーケティング自動化',
    description: 'SNS運用自動化・コンテンツマーケティング支援',
    inLanguage: 'ja',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-autocrew',
    name: 'AutoCrew',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: '業務自動化コンサルティング',
    description: 'LLMによる自動実行エージェント構成・業務最適化',
    inLanguage: 'ja',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-kaoriq',
    name: 'KaoriQ',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'AI駆動EC自動運用',
    description:
      'LLMエージェントによるECサイトの自律運用。コンテンツ生成・SEO・LLMO・商品キュレーションを完全自動化',
    url: 'https://kaoriq.com/',
    inLanguage: 'ja',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-mypcrig',
    name: 'mypcrig',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'AI駆動コンテンツメディア',
    description:
      'LLMエージェントによるPC選定メディアの自律運用。GA4・Search Console連携で検索意図ドリブンの記事生成を自動化',
    url: 'https://mypcrig.com/',
    inLanguage: 'ja',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-legacydram',
    name: 'legacydram',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'AI駆動キュレーションメディア',
    description:
      'LLMエージェントによるウィスキーキュレーションメディアの自律運用。人物軸ストーリー・蒸留化学・銘柄選定を完全自動化',
    url: 'https://legacydram.com/',
    inLanguage: 'ja',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-yureru',
    name: 'Yureru',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: '音楽・クリエイティブ',
    description: '感動の構造化と音楽化プロジェクト',
    inLanguage: 'ja',
  },
];

/** English Service entities for /en/. Same @id as the JP set (one entity, language-tagged). */
export const serviceSchemasEn = [
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-learningmate',
    name: 'LearningMate',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'Educational Content & Publishing',
    description: 'Planning, producing, and selling educational content focused on LLM technologies.',
    inLanguage: 'en',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-ai-loop',
    name: 'AI-Loop',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'Marketing Automation',
    description: 'SNS automation and content marketing support powered by LLM agents.',
    inLanguage: 'en',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-autocrew',
    name: 'AutoCrew',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'Business Automation Consulting',
    description: 'Multi-agent system architecture and business process automation using LLMs.',
    inLanguage: 'en',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-kaoriq',
    name: 'KaoriQ',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'AI-Driven E-Commerce Automation',
    description:
      'Autonomous e-commerce operations powered by LLM agents — content generation, SEO/LLMO, and product curation, fully automated.',
    url: 'https://kaoriq.com/',
    inLanguage: 'en',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-mypcrig',
    name: 'mypcrig',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'AI-Driven Content Media',
    description:
      'Autonomous PC-selection media powered by LLM agents, with a GA4 and Search Console feedback loop and daily auto-publishing.',
    url: 'https://mypcrig.com/',
    inLanguage: 'en',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-legacydram',
    name: 'legacydram',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'AI-Driven Curation Media',
    description:
      'Autonomous whisky curation media powered by LLM agents, distilled through an engineer\'s lens with a people-first editorial policy.',
    url: 'https://legacydram.com/',
    inLanguage: 'en',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    '@id': 'https://propel-lab.co.jp/#service-yureru',
    name: 'Yureru',
    provider: { '@id': 'https://propel-lab.co.jp/#org' },
    serviceType: 'Music & Creative',
    description: 'A music project that captures fleeting emotional moments through music, words, and visuals.',
    inLanguage: 'en',
  },
];

/** LLMO診断レポート (Tier 1 プロダクト化サービス)。/llmo-audit/ と /services/ が参照する。 */
export const llmoAuditServiceSchema = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  '@id': 'https://propel-lab.co.jp/#service-llmo-audit',
  name: 'LLMO診断レポート',
  serviceType: 'LLMO監査・AI検索可視性診断',
  provider: { '@id': 'https://propel-lab.co.jp/#org' },
  description:
    '1ドメインを対象に、llmo-checker全ページスキャン・llms.txt/robots/JSON-LD/canonical/hreflang構造監査・AI検索エンジンでの引用実測・P0/P1/P2優先度付き改善ロードマップを2週間で納品する範囲固定の診断サービス。',
  url: 'https://propel-lab.co.jp/llmo-audit/',
  areaServed: 'JP',
  inLanguage: 'ja',
  offers: {
    '@type': 'Offer',
    price: '98000',
    priceCurrency: 'JPY',
    url: 'https://propel-lab.co.jp/llmo-audit/',
    availability: 'https://schema.org/InStock',
    businessFunction: 'http://purl.org/goodrelations/v1#ProvideService',
  },
};

export const musicGroupSchema = {
  '@context': 'https://schema.org',
  '@type': 'MusicGroup',
  name: 'Yureru',
  alternateName: 'ゆれる',
  description:
    '「心が揺れる」感情の瞬間を音楽・言葉・映像でやさしくすくい上げるプロジェクト。バーチャルシンガーYumei、Silk Reignが所属。',
  genre: ['J-Pop', 'バラード', 'エモ', 'アンビエント'],
  foundingDate: '2024',
  member: [
    {
      '@type': 'Person',
      name: 'Yumei',
      alternateName: 'ユメイ',
      description: 'メインボーカル。繊細な感情を歌に込めるバーチャルシンガー。',
    },
    {
      '@type': 'Person',
      name: 'Silk Reign',
      alternateName: 'シルクレイン',
      description: '洋楽バラードを中心に深い感情を表現するアーティスト。',
    },
  ],
  sameAs: [
    'https://youtube.com/@Yureru-s4n',
    'https://note.com/yureru_propel',
    'https://www.instagram.com/yureru_s4n/',
  ],
  parentOrganization: { '@id': 'https://propel-lab.co.jp/#org' },
};

export const bookSchemas = [
  {
    '@context': 'https://schema.org',
    '@type': 'Book',
    '@id': 'https://propel-lab.co.jp/#book-claude-code-mastery',
    name: '実践Claude Code — コンテキストエンジニアリングで開発が変わる',
    alternateName: 'Practical Claude Code',
    author: { '@type': 'Person', name: 'ken imoto' },
    publisher: { '@type': 'Organization', name: 'Propel-Lab' },
    bookFormat: 'EBook',
    description:
      'Claude Codeの設計思想から、CLAUDE.mdの実践パターン、チーム開発、セキュリティまで。コンテキストエンジニアリングの導入でTypeScript開発の生産性300%向上を実現した全記録。',
    about: [
      'Claude Code',
      'コンテキストエンジニアリング',
      'Context Engineering',
      'CLAUDE.md',
      'AI開発',
      'Vibe Coding',
    ],
    inLanguage: ['ja', 'en'],
    url: 'https://zenn.dev/kenimo49/books/claude-code-mastery',
    isPartOf: {
      '@type': 'BookSeries',
      name: 'エンジニアのためのAI実践シリーズ',
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Book',
    '@id': 'https://propel-lab.co.jp/#book-llmo',
    name: 'なぜあなたのサイトはChatGPTに無視されるのか: LLMO実践ガイド',
    alternateName: 'Why ChatGPT Ignores Your Website: The LLMO Practical Guide',
    author: { '@type': 'Person', name: 'ken imoto' },
    publisher: { '@type': 'Organization', name: 'Propel-Lab' },
    bookFormat: 'EBook',
    description:
      'Google検索で1位を取っても、ChatGPTの回答にあなたのサイトは出てきません。AI検索時代の新しい最適化手法LLMOを実装レベルで解説する実践ガイド。',
    about: [
      'LLMO',
      'LLM Optimization',
      'SEO',
      '構造化データ',
      'JSON-LD',
      'llms.txt',
      'AI検索',
    ],
    inLanguage: ['ja', 'en'],
    isPartOf: {
      '@type': 'BookSeries',
      name: 'エンジニアのためのAI実践シリーズ',
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Book',
    '@id': 'https://propel-lab.co.jp/#book-engineer-psychology-tricks',
    name: 'エンジニアの心理トリック大全 — コードは正しいのに、なぜ提案が通らないのか',
    alternateName: 'Engineer Psychology Tricks: Why Your Proposal Doesn\'t Pass',
    author: { '@type': 'Person', name: 'ken imoto' },
    publisher: { '@type': 'Organization', name: 'Propel-Lab' },
    bookFormat: 'EBook',
    description:
      '20の認知バイアスと心理テクニックをエンジニア実務に翻訳した一冊。システム1/2、AI時代の新バイアス、見積もり/技術選定/デバッグ/コードレビュー/1on1/会議/交渉/心理的安全性/採用面接まで15章でカバー。',
    about: [
      '認知バイアス',
      'エンジニア心理学',
      'システム1/2',
      'コードレビュー',
      '見積もり',
      '1on1',
      '心理的安全性',
      '採用面接',
    ],
    inLanguage: ['ja', 'pt'],
    url: 'https://kenimoto.dev/pt/books/engineer-psychology-tricks',
    sameAs: [
      'https://zenn.dev/kenimo49/books/engineer-psychology-tricks',
      'https://www.amazon.com.br/dp/B0GZFBC7SP',
    ],
    isPartOf: {
      '@type': 'BookSeries',
      name: 'エンジニアのためのAI実践シリーズ',
    },
  },
];
